#cloud-config
users:
  - name: web
    primary_group: web
    groups: wheel
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA/Z6IUM7V6Ujl17UznUYuJ01/FJinqt0OaECEM+Wrcy lab4 key

packages:
  -nginx
  -nmap
